version: "3.9"

services:
    app-webshop-service:
      build: .
      restart: unless-stopped
      ports:
        - "8082:8082"
      environment:
        - api_key=${API_KEY}
        - app_customers_api-url=${APICUSTOMERS_URL}
        - app_products_api-url=${APIPRODUCTS_URL}
        - server_port=8082